[project]
name = "qaagenticai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wanda Hayes", email = "whayeswsfg@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-openai>=1.6.0",
]

[project.scripts]
qaagenticai = "qaagenticai:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
